// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://garqiyrjmykcelnqyolg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdhcnFpeXJqbXlrY2VsbnF5b2xnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwNDg0MzIsImV4cCI6MjA1OTYyNDQzMn0.YUupEC0zH87sfcG-8lYE_Mls0L8w2ZQ6Te8YPWlnGkc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);